### ISSUE TITLE
同一个cname记录，按不同地域分别解析，能处理么？

### ISSUE THREAD

**Issue by feeops** [eryajf/cloud_dns_exporter#18]
同一个cname记录，按不同地域分别解析，能处理么？

**Comment by eryajf** [comment]
目前是遇到什么报错了吗，目前的确没有增加线路的字段，你的需求是想要增加这个字段来区分吗

**Comment by eryajf** [comment]
> 如果是cdn，就需要每一个记录都去解析证书状态

能否举个实际的例子，我好像有点没太理解。同一个cname记录，不同的地域，怎么理解呢？目前项目是从域名解析的维度来展示数据，按说是不冲突的。

**Comment by feeops** [comment]
同一个域名，我让北京联通的用户使用百度CDN，让上海电信的用户使用阿里云CDN，其他地方使用腾讯云CDN

**Comment by crhstack** [comment]
> 同一个CDB域名，我让北京联通的用户使用百度CDN，让上海电信的用户使用阿里云CDN，其他地方使用腾讯云CDN

针对这种不同地域，解析不同的情况，看起来可以将exporter部署到多个地域，这样可以获取到每个地域的证书状态

**Comment by feeops** [comment]
> > 同一个CDB域名，我让北京联通的用户使用百度CDN，让上海电信的用户使用阿里云CDN，其他地方使用腾讯云CDN
> 
> 针对这种不同地域，解析不同的情况，看起来可以将exporter部署到多个地域，这样可以获取到每个地域的证书状态

curl有绑定IP的功能，可以解决这个问题，参考
https://acquia.my.site.com/s/article/360005257154-Use-cURL-s-resolve-option-to-pin-a-request-to-an-IP-address

golang有也有类似的实现

**Comment by eryajf** [comment]
我理解了，关于这个问题，的确是一个相对小众的场景，我考虑下，看看是不是所有的域名记录解析时都把记录值带上，还是说单独处理下。

我再了解下，我看到域名解析里边，会有线路的选择，你这边区域是用的httpdns吗

**Comment by feeops** [comment]
> 我理解了，关于这个问题，的确是一个相对小众的场景，我考虑下，看看是不是所有的域名记录解析时都把记录值带上，还是说单独处理下。
> 
> 我再了解下，我看到域名解析里边，会有线路的选择，你这边区域是用的httpdns吗

不是，阿里云dns就支持这个功能

**Comment by eryajf** [comment]
@crhstack 你评估感觉每个解析都把记录带上怎么样：

```
config := &tls.Config{
	InsecureSkipVerify: true,
	ServerName:         record.FullRecord,
}
d := net.Dialer{
	Timeout: time.Second * 3,
}
conn, err := tls.DialWithDialer(&d, "tcp", record.RecordValue+":443", config)
if err != nil {
	return certInfo, err
}
```

我看应该还好，毕竟默认情况下，连接的地址也是域名所对应的value值，只不过现在给他指定了value。

**Comment by eryajf** [comment]
@feeops 最新的pr已经针对这个场景做了调整，可以再试一试
