### ISSUE TITLE
🐛记录太多的时候会出现 was collected before with the same name and label values

### ISSUE THREAD

**Issue by csh3323** [eryajf/cloud_dns_exporter#19]
![image](https://github.com/user-attachments/assets/41d9432e-29f0-4895-860b-1e4fa747ed19)

was collected before with the same name and label values

**Comment by eryajf** [comment]
使用的版本是哪个版本呢，可以-v查看一下。以及报错信息我记得好像更多一些，可以脱敏截图看下

**Comment by csh3323** [comment]
![image](https://github.com/user-attachments/assets/fbe2af09-7e62-4ab4-9639-4b3bb1ffcd37)
![image](https://github.com/user-attachments/assets/9bd0db40-421b-4968-85e7-03e0f3dd8928)
实际后台拉取记录查看的是唯一的 怀疑是limits的问题

**Comment by eryajf** [comment]
按说腾讯每条记录的record_id应该是唯一的，不应该会有这个错误的。
