### ISSUE TITLE
k8s部署方式下容器的内存一直增加

### ISSUE THREAD

**Issue by 1583669804** [eryajf/cloud_dns_exporter#22]
#### 您使用的版本？ | Your usage version?

cloud_dns_exporter version information: 
  Version:    f5ead1e
  Git Commit: f5ead1e
  Go version: go1.22.2
  OS/Arch:    linux/amd64
  Build Time: 2024-09-17 02:14:3

#### 您做了什么操作？ | What did you do?

增加了一个tencent账号的DNS采集

#### 您遇到了什么问题？ | What are your problems?

容器内存一直增长

#### 您期望的结果是怎样的？ | What is your expected outcome?

1. 容器内存不会一直增长
2. pod resource limit：
cpu request：100 limit 300 
mem request：256MB limit 512MB

3. 监控

![image](https://github.com/user-attachments/assets/978c2c13-f033-4d4a-b581-9475f7a5df91)

**Comment by eryajf** [comment]
这是符合预期的，因为部分数据可能获取会比较久，所以接口没有做成实时返回，而是先放到内存里边。

不过内存不会无限的增长，对象初始化的时候配置了失效时间。

详见： https://github.com/eryajf/cloud_dns_exporter/blob/f5ead1e07c1d9d95bd11ba4d4caed960d9aa24d7/public/public.go#L79

**Comment by 1583669804** [comment]
30天的监控，CPU和内存都在缓慢持续增长

![image](https://github.com/user-attachments/assets/b8afd2ae-69f8-4664-990a-e4cdc4fbaabf)

```
resources: 
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 256Mi
```

**Comment by eryajf** [comment]
> 30天的监控，CPU和内存都在缓慢持续增长
> 
> ![image](https://private-user-images.githubusercontent.com/107526190/385126735-b8afd2ae-69f8-4664-990a-e4cdc4fbaabf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODM1NDcsIm5iZiI6MTczMTM4MzI0NywicGF0aCI6Ii8xMDc1MjYxOTAvMzg1MTI2NzM1LWI4YWZkMmFlLTY5ZjgtNDY2NC05OTBhLWU0Y2RjNGZiYWFiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwMzQ3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTU5NDYwZmJkZDg5MGU0OWRlMjgzNGIyNDdmMTNlYjk3N2RhMzRiMWI5NjcxMmUxMWZhYWFkMWNiNDkyZmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6m8Uo8hzqt1DAvlMJtpyes7j9NImNsOkswDU72ShHn8)
> 
> ```
> resources: 
>   limits:
>     cpu: 1000m
>     memory: 1024Mi
>   requests:
>     cpu: 300m
>     memory: 256Mi
> ```

cpu这个最新版本有做一个修复，可以更新到最新版本试试。内存这个我再看看，会不会还是有漏掉的没回收的。
