### ISSUE TITLE
支持国际知名域名注册提供商

### ISSUE THREAD

**Issue by cdq502** [eryajf/cloud_dns_exporter#7]
比较知名的有：

cloudflare
namecheep

性价比最好的两家，请考虑，谢谢你。

**Comment by eryajf** [comment]
安排

**Comment by eryajf** [comment]
我拉了个开发群，麻烦加下，便于调试内侧：![](https://t.eryajf.net/imgs/2024/09/1725409085035.webp)

**Comment by eallion** [comment]
👀

**Comment by eryajf** [comment]
@cdq502  cloudflare 已经支持，namecheap 看了下，因为我这边没有账号，注册了个，发现api还有限制，暂时无法提供了，只能等后续如果有在用的人，来提交pr了。
